version: '3.5'

x-project-volume:
  &project-volume
  type: bind
  source: ./
  target: /var/www/html

services:
  php:
    container_name: dental-crm-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: dental-crm/php
    volumes:
      - *project-volume
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9000:9000'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    networks:
      - dental-crm
    depends_on:
      - mariadb
  nginx:
    image: dental-crm/nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - *project-volume
    networks:
      - dental-crm
    depends_on:
      - php
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
    networks:
      - dental-crm
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - dental-crm
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - dental-crm
networks:
  dental-crm:
    driver: bridge
